### ISSUE TITLE
Move goglGetProcAddress from cgo to a Go function

### ISSUE THREAD

**Issue by ccherng** [chsc/gogl#12]
Implementing wgl will introduce more files, in new packages presumably. They will need to call goglGetProcAddress as well. From what I've heard cgo functions cannot be called from a different package. Therefore goglGetProcAddress shoud be moved to be a Go function.

What do you think is a good name for the file and where should it go?

For example, github.com/chsc/win32.go and in "package win32" with "+build windows" so that it builds only on windows. Or maybe github.com/chsc/util/windows.go in "package util". There are various options. What do you think is a good one?

**Comment by ccherng** [comment]
Oh I realized the names should be something completely different from what I suggested. I was only thinking about Windows, but since this needs to work cross platform some other name should be needed for the file.

**Comment by ccherng** [comment]
I actually thought through this some more. I think what I proposed in fact does not help the problem. A Cgo function in one package can't call a Go function in another package. In fact I don't see an easy way to implement wgl generation. Ideas?

**Comment by chsc** [comment]
Yes, you can't call C function pointers directly from Go. You need to wrap them with a C function. I think there is no need to extract a simple function like goglGetProcAddress into an external package (It's just a simple wrapper for wglGetProcAddress / dlsym / glxGetProcAddress).
Have you tried to parse the wgl.spec with the binding generator? I think the current goglGetProcAddress implementation should also work with wgl/glx extensions.

**Comment by ccherng** [comment]
More problematic than that. A different package from gl42 will be unable to call goglGetProcAddress at all as far as I understand. The package will be unable to call goglGetProcAddress through Go or Cgo as far as I know. So a wgl package will have no way to use goglGetProcAddress whether from Go or Cgo.

One solution is to have each package essentially duplicate the implementation. Each could have its own goglGetProcAddressMangledName but with a slightly different name.

Another possibility is to move away from a single cross platform file to generating specific files for each platform. This would enable the Windows file the flexibility to base its implementation fully on opengl32.dll and syscall.Syscall() instead of relying on cgo which causes all the problems in linking. This would also have the nice side effect that there would be zero dependencies on header files or static linking to libraries.

**Comment by ccherng** [comment]
So what are you planning for the wgl implementation?

**Comment by chsc** [comment]
Adding support for syscall on windows means that GoGL needs a second generator backend and some rewrites. Currently I don't plan to add such a backend because of the additional maintenance costs.
But I do some GoGL hacking in the coming days to make extension loading (wgl, arb, ext ...) work with the current cgo based generator.

**Comment by ccherng** [comment]
I am curious as to what is your implementation strategy you're going to use. And how does it avoid the problems I described?

**Comment by chsc** [comment]
I've done some tests. It seems that the goglGetProcAddress issue can be easily avoided by declaring goglGetProcAddress as a static function.

**Comment by ccherng** [comment]
Can you show the code you're using to accomplish this? I am unable to reproduce this. The linker still prevents me from referring to goglGetProcAddress in another package.

**Comment by chsc** [comment]
The code is now in the repository. I can import multiple packages without any problems.  Have you recompiled all GoGL packages?

**Comment by ccherng** [comment]
Ok I see what you did. Just duplicate the definition of goglGetProcAddress each time. Where is WGL?

**Comment by chsc** [comment]
Before I'm doing any wgl/glx related stuff, I want to make sure that extension loading works for arb, ext, nv, ... (Some type mapping bugs need to be fixed first). Expect wgl/glx support in the coming days.
