### ISSUE TITLE
The gopher.go sample needs a depth buffer

### ISSUE THREAD

**Issue by jackpal** [chsc/gogl#16]
The gopher sample needs a depth buffer, or else it renders incorrectly. The following patch fixes the problem by passing 16 as the value of OpenWindow's depth argument:

diff --git a/examples/gopher/gopher.go b/examples/gopher/gopher.go
index c28358b..e45be79 100644
--- a/examples/gopher/gopher.go
+++ b/examples/gopher/gopher.go
@@ -35,7 +35,7 @@ func main() {

```
    glfw.OpenWindowHint(glfw.WindowNoResize, 1)

-       if err := glfw.OpenWindow(Width, Height, 0, 0, 0, 0, 0, 0, glfw.Windowed); err != nil {
+       if err := glfw.OpenWindow(Width, Height, 0, 0, 0, 0, 16, 0, glfw.Windowed); err != nil {
            fmt.Fprintf(os.Stderr, "glfw: %s\n", err)
            return
    }
```

**Comment by chsc** [comment]
Thanks. Fixed.
