### ISSUE TITLE
can not compile example in windows and mingw!

### ISSUE THREAD

**Issue by seagatecm** [chsc/gogl#17]
Hi, I use MingW, and try use go and OpenGL.
I try the command but it reports Error!
I dont know the OpenGL binding can work on windows or not.
Thanks for help!

C:\MinGW\go\bin>go get github.com/chsc/gogl/examples/gopher
# github.com/jteeuwen/glfw

callback.go:10: error: enumerator value for `__cgo_enum__0' not integer constant

callback.go:12: error: enumerator value for `__cgo_enum__1' not integer constant

callback.go:14: error: enumerator value for `__cgo_enum__2' not integer constant

callback.go:16: error: enumerator value for `__cgo_enum__3' not integer constant

callback.go:18: error: enumerator value for `__cgo_enum__4' not integer constant

callback.go:20: error: enumerator value for `__cgo_enum__5' not integer constant

callback.go:22: error: enumerator value for `__cgo_enum__6' not integer constant

callback.go:24: error: enumerator value for `__cgo_enum__7' not integer constant

callback.go:26: error: syntax error before "int"
callback.go:28: warning: initialization makes integer from pointer without a cas
t
callback.go:28: error: initializer element is not computable at load time
callback.go:28: error: (near initialization for `__cgodebug_data[0]')
callback.go:29: warning: initialization makes integer from pointer without a cas
t
callback.go:29: error: initializer element is not computable at load time
callback.go:29: error: (near initialization for`__cgodebug_data[1]')
callback.go:30: warning: initialization makes integer from pointer without a cas
t
callback.go:30: error: initializer element is not computable at load time
callback.go:30: error: (near initialization for `__cgodebug_data[2]')
callback.go:31: warning: initialization makes integer from pointer without a cas
t
callback.go:31: error: initializer element is not computable at load time
callback.go:31: error: (near initialization for`__cgodebug_data[3]')
callback.go:32: warning: initialization makes integer from pointer without a cas
t
callback.go:32: error: initializer element is not computable at load time
callback.go:32: error: (near initialization for `__cgodebug_data[4]')
callback.go:33: warning: initialization makes integer from pointer without a cas
t
callback.go:33: error: initializer element is not computable at load time
callback.go:33: error: (near initialization for`__cgodebug_data[5]')
callback.go:34: warning: initialization makes integer from pointer without a cas
t
callback.go:34: error: initializer element is not computable at load time
callback.go:34: error: (near initialization for `__cgodebug_data[6]')
callback.go:35: warning: initialization makes integer from pointer without a cas
t
callback.go:35: error: initializer element is not computable at load time
callback.go:35: error: (near initialization for`__cgodebug_data[7]')
callback.go:36: error: syntax error before "int"

**Comment by chsc** [comment]
This isn't a gogl issue. It's a problem with your glfw installation. Maybe your glfw include path is not set?

**Comment by ghost** [comment]
The gogl binding works fine over here for me: Windows 7 64-bit, Go 1.0.3 64-bit, Mingw-w64 newest build (from TDM-GCC) with GLFW newest stable version (64-bit too) and the glfw package by @jteeuwen
