### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by notnot** [chsc/gogl#19]
What is the current status of OS X support. Is it trivial to implement? 
(I like the fact that gogl doesn't depend on GLEW, that is why I would like to try it out, but I need it to work on OS X)

Hmm, after browsing some source files I do see things that have to do with OS X. Maybe the comment in the readme that OS X support is TODO is outdated?

**Comment by chsc** [comment]
Hi,
I haven't tested it, but it should work on OS X. Let me know if you encounter any problems.

**Comment by ghost** [comment]
Can confirm that this works on OSX. I use the @go-gl / glfw binding. If you want GL 3.2, then before glfw.OpenWindow() you need to request a core profile context, otherwise OSX will just provide a GL 2.1 compatibility context.

Note I haven't tested every single gogl func as-yet of course. Just basic triangle rasterization with simple vertex & frag shaders so far.

**Comment by notnot** [comment]
I have installed gl21 and I am having a problem. I get the following runtime panic:

SDL_GL_core starting up... 2012-11-09 23:44:34.178749 +0100 CET
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x408 pc=0xb74e9749]

goroutine 1 [syscall]:
github.com/chsc/gogl/gl21._Cfunc_goglViewport(0x0, 0x0)
    /tmp/go-build467209207/github.com/chsc/gogl/gl21/_obj/_cgo_defun.c:4578 +0x32
github.com/chsc/gogl/gl21.Viewport(0x0, 0x0, 0x320, 0x258, 0x95824f40, ...)
    /tmp/go-build467209207/github.com/chsc/gogl/gl21/_obj/gl21.cgo1.go:1343 +0x41
main.main()
    /home/jpad/gocode/jpad/src/test/SDL/SDL_GL_core/SDL_GL_core.go:150 +0x38b

gl.Viewport() is the first actual OpenGL function that is called, after gl.Init() which doesn't 
return an error. I am using SDL as the window system layer, with setup code like this:

```
// create an OpenGL window
sdl.GL_SetAttribute(sdl.GL_RED_SIZE, 8)
sdl.GL_SetAttribute(sdl.GL_GREEN_SIZE, 8)
sdl.GL_SetAttribute(sdl.GL_BLUE_SIZE, 8)
sdl.GL_SetAttribute(sdl.GL_DEPTH_SIZE, 16)
sdl.GL_SetAttribute(sdl.GL_DOUBLEBUFFER, 1)

flags := uint32(sdl.RESIZABLE | sdl.OPENGL)
if do_fullscreen {
    flags |= sdl.FULLSCREEN
    sdl.ShowCursor(0)
}
screen = sdl.SetVideoMode(wnd_w, wnd_h, 32, flags)
if screen == nil {
    fmt.Printf("SetVideoMode(): %s\n", sdl.GetError())
    Exit(1)
}
sdl.WM_SetCaption("SDL GL core", "")

sdl.EnableUNICODE(1)
sdl.EnableKeyRepeat(500, 50)

err := gl.Init()
if err != nil {
    panic(fmt.Sprint("gl.Init(): %s", err))
}
gl.Viewport(0, 0, gl.Sizei(wnd_w), gl.Sizei(wnd_h))
```

It looks to me that the OpenGL function pointers have not been initialized?

I am trying this on Ubuntu Linux at the moment, any help is appreciated!

**Comment by notnot** [comment]
Ok, I tried harder and installed glfw. Your example works fine now :) 
I do wonder what is wrong with the SDL variant though, will investigate this further and let you know in case it isn't some stupid mistake of mine...

**Comment by notnot** [comment]
Ah, the "issue" with SDL has been resolved: the panic no longer occurs when you call runtime.LockOSThread() before initializing SDL. Maybe GLFW does this behind the screens automatically.

**Comment by notnot** [comment]
I report success with gl21 + SDL, and gl21 + GLFW :)
Might you be interested to have a gopher_darwin.png, I just made one, but don't know how to send it your way.

It seems time to remove the TODO's OS X support from the documentation. Thanks for sharing your code.

**Comment by chsc** [comment]
I know the readme file is outdated and needs some updates. Please send me your gopher_darwin.png to schunk [dot] christoph [at] googlemail [dot] com. I'll add it to the example directory.

Great to hear that it works on OS X without any problems. The "LockOSThread" thing is a well known issue because OpenGL uses thread local data.
Thank's for testing.
