### ISSUE TITLE
Go string to **gl.Char

### ISSUE THREAD

**Issue by ghost** [chsc/gogl#2]
Hello,

I am converting my OpenGL 3 wiki examples https://github.com/Agon/gl3-examples from the OpenGL binding to your generated OpenGL 3.3 binding. I run into a conversion problem with func ShaderSource(shader Uint, count Sizei, string_ *_Char, length *Int), how do I convert a Go string ([]rune) into a *_gl.Char ?

Thanks in advance.

**Comment by chsc** [comment]
Hi Agon,

when converting my own programs, I also stumbled across this problem. I want to keep the bindings as thin as possible without altering the original OpenGL method signatures to much. My plan is to add some utility functions which convert Go strings to GL strings and vice versa. There will be something like:
func GLStringArray(strs ...string) *\* Char and
func GLStringArrayFree(*\* Char, int)

Maybe future versions of gogl will support alternative method signatures for some "unhandy" functions.
I'll update the repository soon.

**Comment by ghost** [comment]
I see you committed some functions to help out, thank you.
But the func GLStringArray(strs ...string) returns a []_Char which is not required by ShaderSource(), it requires a *_gl.Char . How can I convert the []_Char to a *_gl.Char?

**Comment by chsc** [comment]
Simply write &str[0] to get a pointer to *gl.Char. All arrays and slices have continuous memory in Go. It's like good old C ;) You can do this for every array or data structure you want to pass to the OpenGL bindings.
For example for slices/arrays: gl.Uniform4fv(location, 4, &floatData[0]) or gl.Uniform4fv(loaction, 4, &vector.X) for custom data structures. Just pass the address of the first element of your data structure if it has a continuous memory layout.
I'll add some usage samples to the wiki to clarify this.

**Comment by ghost** [comment]
Thank you.
I got my first example converted and working: https://github.com/Agon/gl3-examples/blob/master/wikibooks/tutorial1/main.go

**Comment by chsc** [comment]
Awesome!
Line 66: // Init glew
GoGL does not depend on GLEW. It has its own extension loading mechanism. Currently only Unix (via glx) is supported. Please let me know if you're interested in porting it to Windows (should work but not tested) and MacOS.

**Comment by ghost** [comment]
Oh, didn't know that GoGL has it*s own extension loading.
That means I don't need to call gl.Init() ?

Yes, I am interested in a Windows port of GoGL. I don't have a Mac, so I can't test my code on MacOS.

Edit: Oh, you are referring to the comment. That comment was from the last OpenGL binding which inits glew with gl.Init() . I will remove that comment.

**Comment by chsc** [comment]
No, you have to call gl.Init() after you have created a valid GL context. It will load all OpenGL extensions/entry points of the package. These are the OpenGL 3.3 functions if you use the gl33 package.

Just have a look at generator.go if you want to port it to another platform. There is a function called goglGetProcAddress (line 112). There is already a wglGetProcAddress for Windows in it. It should work right now but it's not tested.

BTW: Call gl.GLStringArrayFree() after gl.GLStringArray(). See https://github.com/chsc/GoGL/wiki/String-handling

I think I can close the issue. Thanks for porting your OpenGL examples to GoGL.
