### ISSUE TITLE
With manual gen of alfonse tip on Intel HD 4000: "unable to initialize VERSION_1_2"

### ISSUE THREAD

**Issue by metaleap** [chsc/gogl#24]
Now, as per the other thread/issue here today I re-gen'd gogl packages with the tip download of Alfonse. My machine has 2 GPUs I can toggle between with a physical button,a GeForce and an (integrated) Intel "HD 4000".

Previously GoGL had no such issues, but since I re-gen'd it manually today with the tip of alfonse specs, gl42 (still using that one) returns from Init() with "unable to initialize VERSION_1_2" (meaning it can do 1_0 and 1_1). Before I did so, it  initialized all the way to 4_0 which is exactly the GL version implemented by the newest driver release for the HD 4000.

Just a heads up **for you not to re-gen the gogl packages in this repo from the alfonse tip for now**, as this seems to break what previously worked.

(The GeForce has no such issues, still initializes GL up to 4_2 with gl42 package. Still, I'd be reluctant to write this off as "oh well Intel GPUs are just buggy and sucky" when it worked so  fine beforehand.)

Gonna nix my local manual re-gen'd gogl packages and revert to the current gl42 from this repo for now to get back to a working setup with the Intel HD...

[Update: Intel HD 4000 works again now after reverting to the current gl42 package from this repo.]

**Comment by metaleap** [comment]
What's fairly weird now is running your gopher.go on the Intel HD. I have re-downloaded/re-installed gogl completely from this repo just now. Running gopher.go (which uses gl21 -- it wouldn't even compile for gl42 as those deprecated calls aren't available in gl42) ALSO outputs "gl: unable to initialize VERSION_1_2" but nonetheless shows a window and renders the lit rotating gopher box perfectly.

So, I no longer get 1_2 error with **gl42** -- but I _would_ get it with gl21 if I were to use it, and I _would_ get it with the manually gen'd gl42 from alfonse tip if I were to use that one, as well. No idea if these tidbits are in any way helpful to you... what type of machine are you developing/testing this on yourself? If a consumer-grade laptop you just might even have an Intel HD yourself?

**Comment by metaleap** [comment]
One last question: if memory serves, GoGL at one point parsed the XML specs instead of the .spec files, am I correct?

If so, then just out of curiosity why did you switch to .spec parsing? Have Khronos or Alfonse indicated that the XML format will be discontinued / no longer be generated from the .specs periodically?

**Comment by chsc** [comment]
No, gogl never parsed XML files. It always parsed spec files. The first version of gogl used the specs from khronos, later I switched to alfonse's spec files. I have an old Geforce 7300 Go and a graphics card from the Radeon 6400 series. No Intel hardware here.

**Comment by chsc** [comment]
Maybe this problem relates to issue #14? I have no idea why getProcAddress doesn't work correctly on Intel hardware.

**Comment by metaleap** [comment]
Well it worked before!  ;)  may have been a one-off bug, driver's bad hair day or something.

As for issue #14 -- Intel drivers used to have all kinds of issues with core and comp profiles but they've gotten quite good from a GL stability & spec implementation view-point.

It's weird that getProcAddr should work for the 1_0 and 1_1 init stages but then fail somewhere in the 1_2 stage. Even more stunning for gopher.go to still run fine nonetheless (indicating most funcptrs seem to be there). Maybe don't fail on the first funcptr==NULL case you encounter?

I've whipped together a horribly hacky xml-based binding generator last 2-3 days as a little exercise. It is designed to create a blatant clone of a gogl binding, with a few customizations that make sense for me. It also doesn't handle a random missing procaddr as an error per se. It just checks whether a predefined, commonly-needed func at least has a procaddr. This would be glBindSampler for me as I'm targeting 3.3 core or higher. Could be glFramebufferTexture for 3.2 or glClear for 1.0. Quite hacky but OK. This custom thing also lets me include the very few extensions I intend to support right in the binding pkg instead of separate packages with their own gl.Int, gl.Uint types etc... anyway will keep an eye on GoGL as I'm sure my hacky generator will at some point fail  ;D

**Comment by metaleap** [comment]
Just tested https://github.com/go3d/go-opengl/tree/master/cmd/gogl-minimal-app with your newest gl43 (tried both forcing a core profile and not forcing one) and that issue isn't occurring any longer on Intel HD now, so it's all good on this issue  :+1:
