### ISSUE TITLE
What about gl43.DebugMessageCallback()?  ;)

### ISSUE THREAD

**Issue by metaleap** [chsc/gogl#25]
Just a curious case really for the sake of completeness. Don't really need it at this point (though at some point it might really come in handy)...

So there's this new function in GL 4.3 core profile http://www.opengl.org/sdk/docs/man/xhtml/glDebugMessageCallback.xml

When I hacked my own (XML-based) GoGL-rip-off "binding-generator for poor people", I conveniently and lazily skipped this above GL function because I had no idea of how to make it compile with the "callback" arg of type "GLDEBUGPROC"... got some CGO error when generating code for it. As far as I can see the spec-provided passthrough code has some #ifndef typedefs for it, but no less, compiler error.

Just checked out your own newest gl43 build and noticed this functions is missing at your end as well... same reason or are you missing out on some core-profile stuff that in the spec is nonetheless categorized as extensions?

(Really confuses me, this spec stuff: for example, glDebugBlaFoo() functions such as the one above have been added into core 4.3 but spec categorizes them under extension "KHR_debug" -- I don't really grok that "category" stuff fully, for example vertex array functions have been in core since 3.0 but are nonetheless categorized as some ARB_ extension...)

**Comment by chsc** [comment]
Thanks for the hint. Due to some spec changes khr_debug wasn't correctly extracted from gl.spec. I added a simple fix.
I hope all extensions promoted to the core are now in the glXX packages. If you find more of them, let me know.

**Comment by metaleap** [comment]
Oh cool this is neat! The cast to **( \* [0]byte)** looks like pure black magic to me -- my lack of any C experience certainly showing now  ;)
