### ISSUE TITLE
Missing glVertexAttrib variants?

### ISSUE THREAD

**Issue by jayschwa** [chsc/gogl#26]
The OpenGL reference appears to have functions that are not present in gl43. For example, `glVertexAttrib1f()`.
https://www.opengl.org/sdk/docs/man4/xhtml/glVertexAttrib.xml

**Comment by metaleap** [comment]
Deprecated in 3.1 though... sure you want it?  ;)

**Comment by jayschwa** [comment]
Ah, nope! So everything that is generated is not deprecated? Thanks.

**Comment by chsc** [comment]
Hi,

VertexAttrib1f is deprecated and the gl43 package contains no deprecated functionality (as far as the spec is correct). If you want packages with deprecated functionality, simply generate them by your own with `./gogl dlspec && ./gogl gen`. The compatibility package is called gl43c.

It seems that Alfonse's spec file is outdated. There are functions like glVertexAttribI4ui and friends (unlike VertexAttrib1f) which are deprecated in the latest gl.spec from Khronos but not in Alfonse's spec.

**Comment by jayschwa** [comment]
Why is the Alfonses spec used instead of the one from Khronos? What is the
difference?

**Comment by metaleap** [comment]
Stated purpose of Alfonse specs is to provide a bug-free(er) version of the official Khronos specs...
