### ISSUE TITLE
Unsure how to pass a matrix via gl.UniformMatrix4fv

### ISSUE THREAD

**Issue by ysgard** [chsc/gogl#28]
I'm following the Arcsynthesis tutorials and teaching myself OpenGL using this great wrapper, and it's been going swimmingly.  I've reproduced all the C++ code in Go without issues, until now.  I'm wondering if this is a legitimate bug or just me not understanding how to do this with Go-GL.  The exact part I'm stuck on is here:

http://arcsynthesis.org/gltut/Positioning/Tut04%20The%20Matrix%20Has%20You.html

Here's my Go code reproducing it (I've omitted the fragment shader, which is trivial)
https://gist.github.com/Ysgard/5234099

This code is very similar to the one preceding it, which worked.  The main difference is in passing a matrix to a uniform in the shader.  I've tried using both a []gl.Float slice and an [16]gl.Float array for a matrix, but neither seem to work.  This is how I'm trying to pass the matrix to the shader:

gl.UniformMatrix4fv(perspectiveMatrixUnif, 1, gl.FALSE, &theMatrix[0])

I've tried &theMatrix and simply theMatrix, but both of those raise compile-time errors having to do with the type.  If I pass &theMatrix[0], it compiles, but displays a black screen.

Am I passing this array correctly in UniformMatrix4fv?

**Comment by ysgard** [comment]
I accidentally found the answer to my question in an earlier, unrelated issue:

https://github.com/chsc/gogl/issues/2

Though I'm still a little unsure about the purpose of the second number in the function - is it the number of floats that you're passing in through the array, or the number of arrays?  The documentation for OpenGL itself suggests the latter.  

Either way, it looks like I'm back to square one, as changing the number from 1 to 16 doesn't change anything for me.  Still a black screen.

**Comment by metaleap** [comment]
```
gl.UniformMatrix4fv(perspectiveMatrixUnif, 1, gl.FALSE, &theMatrix[0])
```

This is the way I did it and it works with gogl. Your issue is most likely somewhere else..

**Comment by ysgard** [comment]
Damn it I put 

perspectiveMatrixUnif = gl.GetUniformLocation(currentShader, gl.GLString("perspectiveMatrixUnif"))

instead of

perspectiveMatrixUnif = gl.GetUniformLocation(currentShader, gl.GLString("perspectiveMatrix"))

So, problem solved.  Apologies.

**Comment by chsc** [comment]
Just a hint from me when writing OpenGL code: Always check for errors and valid (!=-1) uniform/atttribute locations. This will save you from a lot of head aches ;)

**Comment by ysgard** [comment]
Thanks chsc, the point is well taken.
