### ISSUE TITLE
how to create pointer for array in glBufferData

### ISSUE THREAD

**Issue by Triangle345** [chsc/gogl#29]
I notice that BufferData requires a pointer to the array.  Can someone please list some examples of passing pointers to this.  Thanks!

**Comment by chsc** [comment]
Hello Eugene,
simply cast the address of the first element in your data structure to gl.Pointer:

```
vertices := make([]float, 1024)
gl.BufferData(gl.ARRAY_BUFFER, gl.Sizeiptr(4*len(vertices)), gl.Pointer(&vertices[0]), gl.STATIC_DRAW)
```

Another alternative is gl.Offset(). See wiki: https://github.com/chsc/GoGL/wiki/Passing-arrays-to-VertexAttribPointer

**Comment by Triangle345** [comment]
ah thanks, much appreciated!
