### ISSUE TITLE
Cannot get this VBO example working

### ISSUE THREAD

**Issue by Triangle345** [chsc/gogl#30]
So I'm using Go GL and trying to get a simple VBO example to display but not having any luck.  The equivalent code seems to be working in C.  If anyone could help it would be greatly appreciated!

```
    // calls glortho2d , init etc glfw calls etc
w := Window.NewWindowedWindow("test", 800, 600)

w.Open()

    // simiply sets glclear with white color
w.Clear()

    // wraps glfw swap buffers
w.Refresh()

ID := make([]gl.Uint, 1)
data := make([]float32, 6)
data[0] = 50
data[1] = 50
data[2] = 100
data[3] = 50
data[4] = 74
data[5] = 100
gl.GenBuffers(1, &ID[0])
gl.BindBuffer(gl.ARRAY_BUFFER, ID[0])
gl.BufferData(gl.ARRAY_BUFFER, gl.Sizeiptr(4*len(data)), gl.Pointer(&data), gl.STATIC_DRAW)

gl.Clear(gl.COLOR_BUFFER_BIT)
gl.Color3f(0.0, 0.0, 0.0)
gl.BindBuffer(gl.ARRAY_BUFFER, ID[0])
// 4 is size of our float, but 2 objects each
gl.VertexPointer(2, gl.FLOAT, 2*4, gl.Offset(nil, 0))
gl.DrawArrays(gl.POLYGON, 0, 3)
gl.Flush()
w.Refresh()
time.Sleep(3 * 10e8)
```

I seem to get a white window with nothing on it.  I do not get any errors.

**Comment by chsc** [comment]
You pass a pointer to a slice structure (See http://golang.org/doc/articles/slices_usage_and_internals.html for more information) and not to the first element:

```
gl.BufferData(gl.ARRAY_BUFFER, gl.Sizeiptr(4*len(data)), gl.Pointer(&data), gl.STATIC_DRAW)
```

Try gl.Pointer(&data[0]) instead. Hope that helps.

**Comment by Triangle345** [comment]
Thanks for the quick reply.  I tried giving it the index to the first element like you suggested and still getting a white screen which is odd.    Am I setting the vertex pointer right when using the "offset" as you specify in your notes?

**Comment by Triangle345** [comment]
Hmm well I found out what the problem was:

Seems like I needed to enable the array by:

gl.EnableClientState(gl.VERTEX_ARRAY)

However; i'm trying to use more modern VBO techniques and I know this is deprecated in GL3/4.   If you have any tips on using VBO's the modern way please let me know!

Thanks

**Comment by chsc** [comment]
There is a nice collection of OpenGL tutorials at Wikibooks: http://en.wikibooks.org/wiki/OpenGL_Programming#Modern_OpenGL
I think they are very useful. Especially tutorials 01, 02 and 03 demonstrate the correct use of VBOs in GL 3.x-4.x.

**Comment by Triangle345** [comment]
that is excellent.  Thank you for the helpful comments.
