### ISSUE TITLE
deprecated mach-o/dyld functions

### ISSUE THREAD

**Issue by gordonklaus** [chsc/gogl#4]
On Mac OS X 10.6.8 I'm seeing
cc1: warnings being treated as errors
gl21.go: In function 'goglGetProcAddress':
gl21.go:186: warning: 'NSIsSymbolNameDefined' is deprecated (declared at /usr/include/mach-o/dyld.h:176)
gl21.go:187: warning: 'NSLookupAndBindSymbol' is deprecated (declared at /usr/include/mach-o/dyld.h:179)
gl21.go:189: warning: 'NSAddressOfSymbol' is deprecated (declared at /usr/include/mach-o/dyld.h:188)

Replacing the Apple goglGetProcAddress implementation with
return dlsym(RTLD_DEFAULT, name);
(requires dlfcn.h instead of mach-o/dyld.h)

seems to fix it, but I have no idea if this is really correct!  Maybe you should pass a handle from dlopen() instead of RTLD_DEFAULT.

**Comment by chsc** [comment]
Hi gordonklaus,
thanks for the feedback. I just copied the extension loading code from the Apple developer documentation. I don't own a Mac, so I haven't tested it: http://developer.apple.com/library/mac/#documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_entrypts/opengl_entrypts.html#//apple_ref/doc/uid/TP40001987-CH402-SW6
It would be cool if you send me a patched version of GoGL with a working (and tested) extension loading mechanism for MacOS. You can find the code emitter in generator.go, if you are interested.

Christoph

**Comment by gordonklaus** [comment]
Here's the patch:

diff --git a/generator.go b/generator.go
index 0e0090b..e09b42b 100644
--- a/generator.go
+++ b/generator.go
@@ -69,7 +69,7 @@ func writePackage(w io.Writer, packageName string, pak *Package, functsInfo *F

```
    fmt.Fprintf(w, "// #include <stdlib.h>\n")
    fmt.Fprintf(w, "// #if defined(__APPLE__)\n")
```
-       fmt.Fprintf(w, "// #include <mach-o/dyld.h>\n")
- ```
    fmt.Fprintf(w, "// #include <dlfcn.h>\n")
  fmt.Fprintf(w, "// #include <string.h>\n")
  fmt.Fprintf(w, "// #elif defined(_WIN32)\n")
  fmt.Fprintf(w, "// #define WIN32_LEAN_AND_MEAN 1\n")
  ```
  
  @@ -116,18 +116,7 @@ func writePackage(w io.Writer, packageName string, pak *Package, functsInfo
  
  ```
  fmt.Fprintf(w, "// void* goglGetProcAddress(const char* name) { \n")
  fmt.Fprintf(w, "// #ifdef __APPLE__\n")
  ```
-       fmt.Fprintf(w, "//      NSSymbol symbol;\n")
-       fmt.Fprintf(w, "//      char symbolname[1024];\n")
-       fmt.Fprintf(w, "//      symbolname[0] = '_';\n")
-       fmt.Fprintf(w, "//      strcpy(symbolname + 1, name);\n")
-       fmt.Fprintf(w, "//      symbol = NULL;\n")
-       fmt.Fprintf(w, "//      if(NSIsSymbolNameDefined(symbolname)) {\n")
-       fmt.Fprintf(w, "//              symbol = NSLookupAndBindSymbol(symbolname);\n")
-       fmt.Fprintf(w, "//              if (symbol) {\n")
-       fmt.Fprintf(w, "//                      return NSAddressOfSymbol(symbol);\n")
-       fmt.Fprintf(w, "//              }\n")
-       fmt.Fprintf(w, "//      }\n")
-       fmt.Fprintf(w, "//      return NULL;\n")
-       fmt.Fprintf(w, "//      return dlsym(RTLD_DEFAULT, name);\n")
      fmt.Fprintf(w, "// #elif _WIN32\n")
      fmt.Fprintf(w, "//      void\* pf = wglGetProcAddress((LPCSTR)name);\n")
      fmt.Fprintf(w, "//      if(pf) {\n")
  (it looks like the Git Flavored Markdown destroys this text; any idea how to write verbatim?  at least the email should be unformatted, I hope)

I've never done symbol lookup before; but I read all the documentation, tried some alternatives, and decided that this is the correct way.  Tested and functional for basic gl21 usage.  I didn't try to load any extensions manually, as I'm not familiar with that.

Also, not sure, but I think you want to change the permission bits in MkdirAll and WriteFile in download.go to 0755 and 0644, respectively.  At least, I had to do this before the download and generation would work.

Finally, the newly generated files (at least in gl21) were different from what's currently checked in.  Does this mean the specs have changed, or does it somehow reflect my particular system configuration?

**Comment by chsc** [comment]
OK, I'll change that (dlsym() and directory permissions).
What do you mean with different? The used spec didn't change since the last commit. Maybe it's the order of the emitted spec categories (VERSION_1_1, VERSION_1_2, ... and so on)?

**Comment by gordonklaus** [comment]
I took a closer look...   Yes, mostly it's re-orderings of versions and of constants.  Also, changes from GL Clamp{f,d} types to Float and Double, and Sizei types to Int, e.g.:

-// void (APIENTRYP ptrglClearColor)(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
+// void (APIENTRYP ptrglClearColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);

**Comment by chsc** [comment]
All categories are saved in a Go (hash-)map, so the ordering seems to change after each run. Maybe I'll use a sorted slice to make the generated code more revision control friendly in the future.

I did some investigations for the float/clampf problem. The latest spec changes the parameter types for glClearColor from ClampedColorF to ColorF. I don't know why that was changed.
